version: '3'

services:

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js 
    entrypoint: ./entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on:
      - db

  db: 
    build: 
      dockerfile: Dockerfile            
    image: db
    command: --innodb-use-native-aio=0 
    container_name: db    
    restart: always
    tty: true
    volumes:
    - ./db-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb      
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    volumes:
      - ./nginx:/var/www/html
    tty: true
    ports: 
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge